SET NAMES utf8mb4;
INSERT INTO Coffee(name, shop, type, popularity) VALUES
('美式咖啡', '星巴克', 'Espresso', 0),
('拿铁', '星巴克', 'Espresso', 0),
('馥芮白', '星巴克', 'Espresso', 0),
('冷萃咖啡', '星巴克', 'Cold Brew', 0),
('燕麦拿铁', '星巴克', 'Light Roast', 0),
('生椰拿铁', '瑞幸', 'Espresso', 0),
('厚乳拿铁', '瑞幸', 'Espresso', 0),
('美式咖啡', '瑞幸', 'Espresso', 0),
('丝绒拿铁', '瑞幸', 'Espresso', 0),
('冰吸生椰', '瑞幸', 'Cold Brew', 0),
('手冲咖啡', 'Manner', 'Pour Over', 0),
('拿铁', 'Manner', 'Espresso', 0),
('美式', 'Manner', 'Espresso', 0),
('燕麦拿铁', 'Manner', 'Light Roast', 0),
('冷萃', 'Manner', 'Cold Brew', 0),
('单品手冲', 'Grid', 'Single Origin', 0),
('意式浓缩', 'Grid', 'Espresso', 0),
('拿铁', 'Grid', 'Espresso', 0),
('冷萃', 'Grid', 'Cold Brew', 0),
('燕麦拿铁', 'M Stand', 'Light Roast', 0),
('美式', 'M Stand', 'Espresso', 0),
('手冲', 'M Stand', 'Pour Over', 0),
('冷萃拿铁', 'M Stand', 'Cold Brew', 0),
('招牌浓缩', 'Peets', 'Espresso', 0),
('拿铁', 'Peets', 'Espresso', 0),
('黑眼龙', 'Peets', 'Dark Roast', 0),
('冷萃', 'Peets', 'Cold Brew', 0),
('招牌咖啡', 'Tims', 'Light Roast', 0),
('拿铁', 'Tims', 'Espresso', 0),
('美式', 'Tims', 'Espresso', 0),
('冷萃', 'Tims', 'Cold Brew', 0);